version: '2.0'

language: en

pipeline:
  - name: SpacyNLP
    model: "en_core_web_md"
    case_sensitive: False
  - name: SpacyTokenizer
    "intent_tokenization_flag": False
    "intent_split_symbol": "_"
    "token_pattern": None
  - name: SpacyFeaturizer
    "pooling": "mean"
  - name: "SklearnIntentClassifier"
    kernels: ["linear"]
    "gamma": [0.1]
    "max_cross_validation_folds": 1
    "scoring_function": "f1_weighted"
    
policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy